export default{data:[{title:"Pets' Week",date:"28th September",poster:"/events/pw.png",description:`This World Animals’ Day, Students’ Welfare Committee, Technology Students’
            Gymkhana, gives you an opportunity to express your gratitude and heartfelt love
            towards them by participating in Pets’ Week, 2021 with prizes and gifts worth INR
            10,000 !!`,modalContent:"",content:[`“Until one has loved an animal, a part of one's soul remains unawakened.” --- Anatole
                France, French Poet.
                There’s nothing like the unconditional love of a pet. They show you affection, give you a
                sense of purpose, and greet you every day when you come home. They’re lifelong best
                friends who are always there by your side.
                This World Animals’ Day, Students’ Welfare Committee, Technology Students’
                Gymkhana, gives you an opportunity to express your gratitude and heartfelt love
                towards them by participating in Pets’ Week, 2021 with prizes and gifts worth INR
                10,000 !!`,`For additional details contact: Aditri Vaibhav (+91 8789617065 | aaditri.vaibhav@gmail.com )`],links:[{description:"Register here:",href:"https://docs.google.com/forms/d/e/1FAIpQLSdpA3ObUAhBJqcyaczg0bzuRgMLYnQs_t3LwNgt2D0P-tymyA/viewform",content:"form-link"},{description:"Rules and regulations are available here:",href:"/events/pw-rules-and-regulations.pdf",content:"https://gymkhana.iitkgp.ac.in/events/pw-rules-and-regulations.pdf"}]},{title:"Covid-19 Awareness Video making Competition",date:"15th September",poster:"/events/covid19.png",description:`Technology Students' Gymkhana is organizing an online video-making competition to provide a platform for the students of IIT Kharagpur to channel their inner movie-makers to deliver an important message creatively.`,modalContent:"",content:[`Technology Students’ Gymkhana is organizing an online video-making competition to provide a platform for the students of IIT Kharagpur to channel their inner movie-makers to deliver an important message creatively. They will not only get the opportunity to showcase their video-making skills but also raise awareness about the current scenario of rising cases and ensure that the necessary protocols will be followed if students are called back to campus. The top 3 winners will also receive exciting cash prizes. \n
                The deadline for registration is 5th September, 11:59 PM. 
                Guidelines regarding the submission will be emailed to those who register through the aforementioned form.
                The deadline for the submission is 15th September, 11:59 pm.`],links:[{description:"Rules for the Competition are:",href:"https://docs.google.com/document/d/1CEGbO5mcqKhCwwwgLYozL8FbjhF2P8TtSIt4DeL-akE/edit?usp=sharing",content:"https://docs.google.com/document/d/1CEGbO5mcqKhCwwwgLYozL8FbjhF2P8TtSIt4DeL-akE/edit?usp=sharing"},{description:"Prior Registration is required, link for the registration:",href:"https://forms.gle/PaG1y3Swdfg31uVB6",content:"https://forms.gle/PaG1y3Swdfg31uVB6"}]},{title:"Monthly Art Challenge: PAINT-DEMIC",date:"30th September",poster:"/events/paint-demic.jpg",description:`September is here and some students are coming back to campus. This brings with it the possibility of an outbreak and hence adhering to Covid protocols is of paramount importance. To protect our community, it is required that each one of us is well aware of the rules and regulations set in place. Incoming students will have to quarantine for a minimum duration of one week. Students are advised not to leave their rooms unnecessarily, wear masks and maintain social distancing.`,modalContent:"",content:[`September is here and some students are coming back to campus. This brings with it the possibility of an outbreak and hence adhering to Covid protocols is of paramount importance. To protect our community, it is required that each one of us is well aware of the rules and regulations set in place. Incoming students will have to quarantine for a minimum duration of one week. Students are advised not to leave their rooms unnecessarily, wear masks and maintain social distancing.

                To share this message, Technology Students’ Gymkhana has collaborated with Spectra to bring forward this awareness campaign. Art is captivating and has the potential to be infinitely memorable. The monthly art prompt for September is ‘Paint-demic’ with the purpose of using art to support the well being of our student community.
                
                We are looking for artworks depicting the importance of the Covid protocols, the dangers of the virus or healthy habits amidst a pandemic. The most creative artworks will be put up at various locations on campus to invigorate the spirits of students staying there and spread awareness regarding the rules set in place. The best artworks would be displayed by Gymkhana on Facebook.
                
                All sorts of artworks are appreciated, paintings, digital or traditional, sketches, posters, comics etc. Use any medium of your choice.
                Good luck to all the participants!
                Stay safe everyone!`],links:[{description:"Rules are available here:",href:"https://docs.google.com/document/d/1-0VHjfGnvaUcXcoZSrqz5a3HbZVAl4JDGu7BUp8NaxU/edit",content:"https://docs.google.com/document/d/1-0VHjfGnvaUcXcoZSrqz5a3HbZVAl4JDGu7BUp8NaxU/edit"},{description:"Please submit your artworks here at:",href:"https://docs.google.com/forms/d/e/1FAIpQLSfB6mZ3T7WrQrgXLMPy_YmVeau87INZIU-Gmd3bW62w1XxX2w/viewform?usp=sf_link",content:"https://docs.google.com/forms/d/e/1FAIpQLSfB6mZ3T7WrQrgXLMPy_YmVeau87INZIU-Gmd3bW62w1XxX2w/viewform?usp=sf_link"}]}]};